services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KimaiPlugin\InvoiceEmailerBundle\:
    resource: '../../*'
    exclude:
      - '../../Resources/'

  KimaiPlugin\InvoiceEmailerBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
