parameters:
  env(INVOICE_EMAILER_AUTO_SEND): '0'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KimaiPlugin\InvoiceEmailerBundle\:
    resource: '../../*'
    exclude:
      - '../../Resources/'
      - '../../doc/'
      - '../../tests/'

  KimaiPlugin\InvoiceEmailerBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']


  KimaiPlugin\InvoiceEmailerBundle\Service\AutomaticInvoiceEmailService:
    arguments:
      $enabled: '%env(bool:INVOICE_EMAILER_AUTO_SEND)%'
